name: Update Issues Assignees

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: assignees update
      uses: garganshu/github-label-updater@v1.0.0
      with:
        owner: ${{secrets.OWNER}}
        repo: ${{secrets.REPO}}
        token: ${{secrets.TOKEN}}
        filter-labels: ready-for-review
        clear-assignees: false
        update-assignees: username
        